config/routes.rb
Rails.application.routes.draw do
  root 'search#index'
  
  get '/login' => 'sessions#new', :as => :login 
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/register' => 'sessions#register', :as => :register
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  
  get 'profile' => 'users#edit', :as => :user
  put 'profile' => 'users#update'

  # get '/import' => 'import#show'
  # put '/import' => 'import#upload'
  
  get '/search' => 'search#index'
  resources :equivalencies
  get '/my-equivalencies/' => 'equivalencies#user'

  get '/admin'  => 'admin#index', :as => :admin

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Course Database</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
        
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mainNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Course Database</a>
            </div>
            <div class="collapse navbar-collapse" id="mainNavbar">
                <ul class="nav navbar-nav" role="tablist">
                    <li class="<%= 'active' if current_page?(search_path) || current_page?(root_path) %>"><%= link_to 'Search Courses', search_path %></li>

                    <% if current_user && current_user.admin %>
                    <li class="<%= 'active' if current_page?(equivalencies_path) %>"><%= link_to 'Reviews', equivalencies_path(:status => :pending) %></li>
                    <% end %>

                    <% if current_user && !current_user.admin %>
                    <li class="<%= 'active' if current_page?(my_equivalencies_path) %>"><%= link_to 'My Reviews', my_equivalencies_path %></li>
                    <% end %>

                    <li class="<%= 'active' if current_page?(new_equivalency_path) %>"><%= link_to 'Submit a review', new_equivalency_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <% if current_user %>
                        
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <%= current_user.name %>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'My Profile', profile_path %></li>
                            <% if current_user && current_user.admin %>
                            <li><%= link_to 'Administrator Options', admin_path %></li>
                            <% end %>
                            <li><%= link_to 'Sign Out', logout_path %></li>
                        </ul>
                    </li>
                        
                    <% else %>
                    
                    <li><%= link_to 'Sign In or Register', login_path %></li>
                    
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
        
    
    <div class="container">
       
        <div class="row text-center">
            <div class="col-md-8 col-md-offset-2">
                <% flash.each do |name, msg| %>
                <%= content_tag :div, msg, :class => "alert alert-#{name}" %>
                <% end %>
            </div>
        </div>
            
        <div class="row">

            <%= yield %>
        
        </div>

<% if current_user && current_user.admin && !@print_view%>
        <div class="row text-center small">
            <br><br>
            questions? bugs? feature requests? <a href="http://github.com/mrysav/courseman">check us out on github</a>!
        </div>
<% end %>

    </div>

</body>
</html>